config/routes.rb
Gallery::Application.routes.draw do
  get "canvases/index"

  get "canvases/choise_canvas"

  resources :paintings do
    member do
      post :sendEmail
    end
  end
  root to: 'static_pages#index'
  # root to: 'paintings#index'
  post 'paintings/sendEmail'
  post 'paintings/index'
  post 'payments/order'
  post 'call/order'
  post 'payments/setSrcImage'
  post 'payments/afterPay'
  post 'call/order_call'
  post 'static_pages/index'
  get 'canvases/index'
  post 'canvases/choice_canvas'
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  attr_accessible :image, :name
  mount_uploader :image, ImageUploader

  belongs_to :user

  before_create :default_name

  def default_name
    self.name ||= File.basename(image.filename, '.*').titleize if image
  end
end

app/models/user.rb
# require '../../app/models/user'
class User < ActiveRecord::Base
  attr_accessible :email, :lastName, :token

  has_many :paintings

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.token = User.encrypt(User.new_remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/call_controller.rb
class CallController < ApplicationController
  def order
  end

  def order_call
    email = 'dsuschinsky@gmail.com'
    name = params[:name_zakaz]
    phone = params[:phone_zakaz]
    text_area = params[:text_area_zakaz]
    puts name
    puts phone
    puts text_area
    ImageMailer.welcome_email_order_call(email, name, phone, text_area).deliver
    respond_to do |format|
      format.html { redirect_to :back }
    end
  end
end

app/controllers/canvases_controller.rb
class CanvasesController < ApplicationController

  before_filter :get_user

  def index
    @template = 'template1';
    @paintings = @user.paintings
  end

  def choice_canvas
    @template = params[:template]
    respond_to do |format|
      format.js {}
    end
  end

  private

  def get_user
    token = cookies['image_user_token']
    if token == nil
      create_new_token_and_user
    else
      @user = User.find_by_token(User.encrypt(token))
      if @user.nil?
        create_new_token_and_user
      end
    end
  end

  def create_new_token_and_user
    new_token = User.new_remember_token
    encrypt = User.encrypt(new_token)
    @user = User.create
    @user.token = encrypt
    @user.save!
    cookies['image_user_token'] = new_token
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController

  before_filter :get_user

  def index
    @paintings = @user.paintings
  end

  def show
    @painting = Painting.find(params[:id])
  end

  def new
    @painting = Painting.new
  end

  def create
    @painting = Painting.create(params[:painting])
    @painting.user = @user
    @painting.save
  end

  def edit
    @painting = Painting.find(params[:id])
  end

  def update
    @painting = Painting.find(params[:id])
    if @painting.update_attributes(params[:painting])
      redirect_to paintings_url
    else
      render :edit
    end
  end

  def destroy
    @painting = Painting.find(params[:id])
    @painting.destroy
    redirect_to paintings_url
  end

  private

  def get_user
    token = cookies['image_user_token']
    if token == nil
      create_new_token_and_user
    else
      @user = User.find_by_token(User.encrypt(token))
      if @user.nil?
        create_new_token_and_user
      end
    end
  end

  def create_new_token_and_user
    new_token = User.new_remember_token
    encrypt = User.encrypt(new_token)
    @user = User.create
    @user.token = encrypt
    @user.save!
    cookies['image_user_token'] = new_token
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def order
  end

  def afterPay
    email = 'dsuschinsky@gmail.com'
    image_src = "public/assets/"+cookies['image_user_token']+".png"
    fio = params[:fio]
    cost = params[:money]
    phone = params[:phone]
    email_user = params[:email]
    address = params[:address]
    count = params[:count]
    money = params[:money]

    case params[:delivery]
      when "post delivery"
      when "free delivery"
      when nil
        @req_message = "request type is not selected"
    end

    # ImageMailer.welcome_email(email, image_src, fio, phone, email_user, address, count, money).deliver
    ImageMailer.welcome_email(email, fio, cost, phone, email_user, address, count, money, image_src).deliver
  end

  def setSrcImage
    src = params[:srcImage]
    image_data = Base64.decode64(src['data:image/png;base64,'.length .. -1])
    image_path = "public/assets/"+cookies['image_user_token']+".png"
    thumb_path = "public/assets/"+cookies['image_user_token']+"_thumb.png"
    File.open(image_path, 'wb') do |f|
      f.write image_data
    end
    resize_image image_path, thumb_path
    render nothing: true
  end

  def resize_image image_path, thumb_path
    image = Magick::Image::read(image_path).first
    image.resize_to_fit!(150)
    image.write(thumb_path)
    image.destroy!
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/canvases_helper.rb
module CanvasesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/canvases/choice_canvas.js.erb
$('#div_render').html("<%= j (render partial: 'canvases/templates/template', locals: {template: @template}) %>");

app/views/canvases/templates/_template.html.erb
<%= render 'canvases/templates/'+@template %>

app/views/canvases/templates/_template1.html.erb
<!--<h1>template1</h1>-->
<div id="canvas-container" style="width: 400px; height: 400px;">
  <div class="div_for_canvas" id="template_1_1" style="float:left;width: 400px !important; height: 200px !important;"
       c_top="0.25" c_left="0.5" c_height="0.5" c_width="1">
    <!--<canvas style="width: 400px !important; height: 200px !important;" class="canvases" id="canvas_template_1_1"-->
            <!--c_top="0.25" c_left="0.5" c_height="0.5" c_width="1">-->
    <!--</canvas>-->
  </div>
  <div class="div_for_canvas" id="template_1_2" style="float:left;width: 400px !important; height: 200px !important;"
       c_top="0.75" c_left="0.5" c_height="0.5" c_width="1">
    <!--<canvas style="width: 400px !important; height: 200px !important;" class="canvases" id="canvas_template_1_2"-->
            <!--c_top="0.75" c_left="0.5" c_height="0.5" c_width="1">-->
    <!--</canvas>-->
  </div>
</div>

app/views/canvases/templates/_template2.html.erb
<!--<h1>template2</h1>-->
<div id="canvas-container" style="width: 400px; height: 400px;">
  <div class="div_for_canvas" id="template_2_1" style="float:left; width: 266px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_2_1" style="float:left; width: 266px !important; height: 133px !important;"
            c_top="0.165" c_left="0.335" c_height="0.33" c_width="0.665">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_2_2" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_2_2" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.165" c_left="0.832" c_height="0.33" c_width="0.335">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_2_3" style="float:left; width: 200px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_2_3"  style="float:left; width: 200px !important; height: 133px !important;"
            c_top="0.495" c_left="0.25" c_height="0.33" c_width="0.5">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_2_4" style="float:left; width: 200px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_2_4" style="float:left; width: 200px !important; height: 133px !important;"
            c_top="0.495" c_left="0.75" c_height="0.33" c_width="0.5">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_2_5" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_2_5" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.825" c_left="0.168" c_height="0.33" c_width="0.335">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_2_6" style="float:left; width: 266px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_2_6" style="float:left; width: 266px !important; height: 133px !important;"
            c_top="0.825" c_left="0.66" c_height="0.33" c_width="0.665">
    </canvas>
  </div>
</div>

app/views/canvases/templates/_template3.html.erb
<!--<h1>template3</h1>-->
<div id="canvas-container" style="width: 400px; height: 400px;">
  <div class="div_for_canvas" id="template_3_1" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_1" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_2" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_2" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.125" c_left="0.375" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_3" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_3" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.125" c_left="0.625" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_4" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_4" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.125" c_left="0.875" c_height="0.25" c_width="0.25">
    </canvas>
  </div>


  <div style="float:left; width: 100px !important; height: 200px !important;">
  <div class="div_for_canvas" id="template_3_5" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_5" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.375" c_left="0.125" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_8" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_8" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.375" c_left="0.125" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  </div>


  <div class="div_for_canvas" id="template_3_6" style="float:left; width: 200px !important; height: 200px !important;">
    <canvas class="canvases" id="canvas_template_3_6" style="float:left; width: 200px !important; height: 200px !important;"
            c_top="0.5" c_left="0.5" c_height="0.5" c_width="0.5">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_7" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_7" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.375" c_left="0.875" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_9" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_9" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.625" c_left="0.875" c_height="0.25" c_width="0.25">
    </canvas>
  </div>


  <div class="div_for_canvas" id="template_3_10" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_10" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.875" c_left="0.125" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_11" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_11" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.875" c_left="0.375" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_12" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_12" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.875" c_left="0.625" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_3_13" style="float:left; width: 100px !important; height: 100px !important;">
    <canvas class="canvases" id="canvas_template_3_13" style="float:left; width: 100px !important; height: 100px !important;"
            c_top="0.875" c_left="0.875" c_height="0.25" c_width="0.25">
    </canvas>
  </div>
</div>

app/views/canvases/templates/_template4.html.erb
<!--<h1>template4</h1>-->
<div id="canvas-container" style="width: 400px; height: 400px;">
  <div style="float: left; width: 50%; height: 33%;">
    <div class="div_for_canvas" id="template_4_1" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_1" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_2" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_2" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_3" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_3" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_4" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_4" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
  </div>

  <div style="float: left; width: 50%; height: 33%;">
    <div class="div_for_canvas" id="template_4_5" style="float:left; width: 200px !important; height: 134px !important;">
      <canvas class="canvases" id="canvas_template_4_5" style="float:left; width: 200px !important; height: 134px !important;"
              c_top="0.825" c_left="0.25" c_height="0.33" c_width="0.5">
      </canvas>
    </div>
  </div>

  <div style="float: left; width: 50%; height: 33%;">
    <div class="div_for_canvas" id="template_4_6" style="float:left; width: 200px !important; height: 134px !important;">
      <canvas class="canvases" id="canvas_template_4_6" style="float:left; width: 200px !important; height: 134px !important;"
              c_top="0.825" c_left="0.25" c_height="0.33" c_width="0.5">
      </canvas>
    </div>
  </div>
  <div style="float: left; width: 50%; height: 33%;">
    <div class="div_for_canvas" id="template_4_7" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_7" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_8" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_8" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_9" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_9" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_10" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_10" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
  </div>

  <div style="float: left; width: 50%; height: 33%;">
    <div class="div_for_canvas" id="template_4_11" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_11" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_12" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_12" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_13" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_13" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
    <div class="div_for_canvas" id="template_4_14" style="float:left; width: 100px !important; height: 67px !important;">
      <canvas class="canvases" id="canvas_template_4_14" style="float:left; width: 100px !important; height: 67px !important;"
              c_top="0.125" c_left="0.125" c_height="0.25" c_width="0.25">
      </canvas>
    </div>
  </div>

  <div style="float: left; width: 50%; height: 33%;">
    <div class="div_for_canvas" id="template_4_15" style="float:left; width: 200px !important; height: 134px !important;">
      <canvas class="canvases" id="canvas_template_4_15" style="float:left; width: 200px !important; height: 134px !important;"
              c_top="0.825" c_left="0.25" c_height="0.33" c_width="0.5">
      </canvas>
    </div>
  </div>
</div>

app/views/canvases/templates/_template5.html.erb
<!--<h1>template5</h1>-->
<div id="canvas-container" style="width: 400px; height: 400px;">
  <div class="div_for_canvas" id="template_5_1" style="float:left; width: 200px !important; height: 200px !important;"
       c_top="0.25" c_left="0.25" c_height="0.5" c_width="0.5">
    <!--<canvas class="canvases" id="canvas_template_5_1" style="float:left; width: 200px !important; height: 200px !important;"-->
            <!--c_top="0.25" c_left="0.25" c_height="0.5" c_width="0.5">-->
    <!--</canvas>-->
  </div>
  <div class="div_for_canvas" id="template_5_2" style="float:left; width: 200px !important; height: 200px !important;"
       c_top="0.25" c_left="0.75" c_height="0.5" c_width="0.5">
    <!--<canvas class="canvases" id="canvas_template_5_2" style="float:left; width: 200px !important; height: 200px !important;"-->
            <!--c_top="0.25" c_left="0.75" c_height="0.5" c_width="0.5">-->
    <!--</canvas>-->
  </div>
  <div class="div_for_canvas" id="template_5_3" style="float:left; width: 200px !important; height: 200px !important;"
       c_top="0.25" c_left="0.75" c_height="0.5" c_width="0.5">
    <!--<canvas class="canvases" id="canvas_template_5_3" style="float:left; width: 200px !important; height: 200px !important;"-->
            <!--c_top="0.75" c_left="0.25" c_height="0.5" c_width="0.5">-->
    <!--</canvas>-->
  </div>
  <div class="div_for_canvas" id="template_5_4" style="float:left; width: 200px !important; height: 200px !important;"
       c_top="0.25" c_left="0.75" c_height="0.5" c_width="0.5">
    <!--<canvas class="canvases" id="canvas_template_5_4" style="float:left; width: 200px !important; height: 200px !important;"-->
            <!--c_top="0.75" c_left="0.75" c_height="0.5" c_width="0.5">-->
    <!--</canvas>-->
  </div>
</div>

app/views/canvases/templates/_template6.html.erb
<!--<h1>template6</h1>-->
<div id="canvas-container" style="width: 400px; height: 400px;">
  <div class="div_for_canvas" id="template_6_1" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_1" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.165" c_left="0.165" c_height="0.33" c_width="0.33">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_6_2" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_2" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.165" c_left="0.5" c_height="0.33" c_width="0.33">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_6_3" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_3" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.165" c_left="0.825" c_height="0.33" c_width="0.33">
    </canvas>
  </div>

  <div class="div_for_canvas" id="template_6_4" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_4" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.5" c_left="0.165" c_height="0.33" c_width="0.33">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_6_5" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_5" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.5" c_left="0.5" c_height="0.33" c_width="0.33">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_6_6" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_6" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.5" c_left="0.825" c_height="0.33" c_width="0.33">
    </canvas>
  </div>

  <div class="div_for_canvas" id="template_6_7" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_7" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.825" c_left="0.165" c_height="0.33" c_width="0.33">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_6_8" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_8" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.825" c_left="0.5" c_height="0.33" c_width="0.33">
    </canvas>
  </div>
  <div class="div_for_canvas" id="template_6_9" style="float:left; width: 133px !important; height: 133px !important;">
    <canvas class="canvases" id="canvas_template_6_9" style="float:left; width: 133px !important; height: 133px !important;"
            c_top="0.825" c_left="0.825" c_height="0.33" c_width="0.33">
    </canvas>
  </div>

</div>

app/views/canvases/templates/_template8.html.erb
<!--<h1>template8</h1>-->
<div id="canvas-container" style="width: 400px; height: 400px;">
  <div class="div_for_canvas" id="template_8_1" style="float:left; width: 400px !important; height: 400px !important;">
    <canvas class="canvases" id="canvas_template_8_1" style="float:left; width: 400px !important; height: 400px !important;"
            c_top="1" c_left="1" c_height="1" c_width="1">
    </canvas>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Фото-подушки</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <meta name="description" content=""/>

  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag 'bootstrap.css' %>
  <%= stylesheet_link_tag 'bootstrap-image-gallery.css' %>
  <%= stylesheet_link_tag 'bootstrap-theme.css' %>
  <%= stylesheet_link_tag 'styles.css' %>
  <%= stylesheet_link_tag 'styleLaptop.css' %>
  <%= stylesheet_link_tag 'styleTablet.css' %>
  <%= stylesheet_link_tag 'fonts/font-awesome.css' %>
  <%= stylesheet_link_tag 'fonts/font-awesome.css.erb' %>
  <%= stylesheet_link_tag 'fonts/font-awesome.min.css' %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>

  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://blueimp.github.io/Gallery/css/blueimp-gallery.min.css">

</head>
<body>
<div id="container">
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/paintings/_form.html.erb
<%= form_for @painting do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>
      <ul>
      <% @painting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <p>
    <%= f.file_field :image, multiple: true, name: "painting[image]" %>
  </p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<div class="painting">
  <%=  image_tag(painting.image_url(:thumb), class: 'dragImg ui-widget-content', draggable: 'true') if painting.image? %>
  <div class="actions">
    <!--<%= link_to "edit", edit_painting_path(painting) %> |-->
    <%= link_to "удалить", painting, :confirm => 'Вы уверены ?', :method => :delete %>
  </div>
</div>

app/views/paintings/create.js.erb
<% if @painting.new_record? %>
  alert("Failed to upload file: <%= j @painting.errors.full_messages.join(', ').html_safe %>");
<% else %>
$("#paintings").append("<%= j render(@painting) %>");
<% end %>

app/views/paintings/edit.html.erb
<h1>Editing Painting</h1>

<%= render 'form' %>

app/views/paintings/new.html.erb
<h1>Add a Painting</h1>

<%= render 'form' %>

app/views/paintings/show.html.erb
<h1><%= @painting.name %></h1>

<p><%= image_tag @painting.image_url %></p>

<p>
  <%= link_to "Edit", edit_painting_path(@painting) %> |
  <%= link_to "Destroy", @painting, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Paintings", paintings_path %>
</p>

app/views/payments/afterPay.html.erb
<h1>Вы успешно заказали какую-то хрень</h1>